### ISSUE TITLE
Dockerfile not found at docker build

### ISSUE THREAD

**Issue by JohanHardy** [eclipse-cdt-cloud/cdt-cloud-blueprint#71]
### Steps to Reproduce:

1. Using docker desktop for windows
2. go to the repo location
3. execute the documented docker build

### Additional Information

- Operating System: Windows MS
- Theia Version: n/a

**Comment by sgraband** [comment]
The issue is that on Windows the path <repo>/Dockerfile (file in root) and <repo>/dockerfile (folder in root) are treated the same. Hence when copying or cloning the project the `dockerfile` folder is not created.

I will provide a PR where i rename everything accordingly and update the documentation.
